// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgVJ1hhdAHf6TQGXE_bmrjODt6juFZL3o',
    appId: '1:867699745981:android:b287e6d5487b614a0643d4',
    messagingSenderId: '867699745981',
    projectId: 'hockauth-16e4e',
    storageBucket: 'hockauth-16e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAolEcAhcVj9_hQzGodbkOsshZxQC3CCI',
    appId: '1:867699745981:ios:e41d908379a559950643d4',
    messagingSenderId: '867699745981',
    projectId: 'hockauth-16e4e',
    storageBucket: 'hockauth-16e4e.firebasestorage.app',
    iosClientId:
        '867699745981-mh82dh2aa9a8cidqbuc0jddg0tkfp01l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjO7xTp4ZLASrMe55nez1dJPLYuryvOw',
    appId: '1:867699745981:web:f7c3e9b358f5f1f00643d4',
    messagingSenderId: '867699745981',
    projectId: 'hockauth-16e4e',
    authDomain: 'hockauth-16e4e.firebaseapp.com',
    storageBucket: 'hockauth-16e4e.firebasestorage.app',
    measurementId: 'G-T7ZNEC7SJG',
  );
}
